server:
  image: python:3
  working_dir: /mnt
  volumes:
    - .:/mnt
  links:
   - db
  ports:
    - '5000:5000'
  environment:
    PYTHONPATH: $PYTHONPATH:src
    PYTHONUSERBASE: /mnt/vendor
    IMPORT_PATH: /mnt/test/fixture
  command: python src/server.py

db:
  image: mongo:3.6
  volumes:
- shared/data:/var/lib/mongo/data